### ISSUE TITLE
Daily sequences are not counting

### ISSUE THREAD

**Issue by pump61** [OakLoaf/LushRewards#19]
I'm testing the plugin mode by mode, as it is necessary to wait a day to count, the tests take time, well the rewards have been configured but every day that players enter doing a login sequence it always stays on day 1, it never continues, I've already set different default, streak, online_only modes and the same problem remains

Lush Rewards Version: 3.2.0
Server Version: Purpur-2176 (MC: 1.20.4)*
![image](https://github.com/user-attachments/assets/3eb71eca-bb93-4e31-8e6a-9f98f339e3da)

**Comment by pump61** [comment]
sended

**Comment by pump61** [comment]
https://mclo.gs/YWceNuX

**Comment by OakLoaf** [comment]
You have `reset-days-at` set to `1` meaning it is resetting the players every single day meaning it's impossible to get past day 1
